name: Deploy documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Copy requirements
      run: |
        mkdir -p temp_files
        cp requirements.txt temp_files/.

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
  
    - name: Clean old documentation
      run: |
        cd gh-pages/
        rm -rf docs/

    - name: Paste requirements to gh-pages
      run: cp temp_files/requirements.txt gh-pages/.

    - name: Install dependencies
      run: |
        cd gh-pages/
        sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
        python -m pip install --upgrade pip
        sed -i 's/#-/-/' requirements.txt
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=gh-pages" >> $GITHUB_ENV

    - name: Generate documentation
      run: |
        cd gh-pages/
        make html

    - name: Add personalized index.html
      run: |
        cd gh-pages
        python scripts/generate_index.py | tee index.html

    - name: Configure Git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Push changes
      run: |
        cd gh-pages
        rm -rf src/cryptoevolutionpackage || true
        git add .
        git reset requirements.txt
        git commit -m "[DOC] Deploy documentation from ${{ github.sha }}"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
