name: Deploy content to pages

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy documentation"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/gh-pages' || github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=gh-pages" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.'
          name: gh-pages-artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: gh-pages-artifact