name: Gradient workflow

on:
  workflow_dispatch:

jobs:
  gradient:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run gradient command
      env:
        GRADIENT_API_KEY: ${{ secrets.GRADIENT_API_KEY }}
        GRADIENT_PROJECT_ID: ${{ secrets.GRADIENT_PROJECT_ID }}
      run: |
        python scripts/run_gradient_command.py \
          --url https://github.com/${{ github.repository }}.git \
          --command "echo test > test.txt && gradient notebooks delete --id `hostname` --apiKey $API_KEY" \
          --env API_KEY:$GRADIENT_API_KEY