name: Run tests

on:
  push:
    branches:
      - 'working_branch'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests
      run: |
        pytest --cov-config=.coveragerc --cov=source --cov-report=html --html=report.html
      
    - name: Copy reports
      if: ${{ success() }}
      run: |
        mkdir -p temp_files
        cp -r htmlcov temp_files/.
        rm -r temp_files/htmlcov/.gitignore
        cp report.html temp_files/.
        cp assets/style.css temp_files/.

    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Get current date
      id: get_date
      run: echo "DATE=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Paste reports to gh-pages
      run: |
        mkdir -p gh-pages/reports
        mkdir -p gh-pages/reports/assets
        mkdir -p gh-pages/reports/$DATE
        cp -r temp_files/htmlcov gh-pages/reports/$DATE/.
        cp temp_files/report.html gh-pages/reports/$DATE/.
        cp temp_files/style.css gh-pages/reports/assets/.
        sed -i 's|<link href="assets/style.css" rel="stylesheet" type="text/css"/>|<link href="../assets/style.css" rel="stylesheet" type="text/css"/>|' gh-pages/reports/$DATE/report.html
        sed -i '/<\/html>/i\  <h2> Coverage </h2>\n  <p> Go to <a href="htmlcov\\index.html"> report </a></p>' gh-pages/reports/$DATE/report.html

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=gh-pages" >> $GITHUB_ENV

    - name: Create index.html with links to all reports
      run: |
        cd gh-pages
        python scripts/generate_index.py | tee index.html

    - name: Configure Git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Push changes
      run: |
        cd gh-pages
        git add .
        git commit -m "[DOC] Deploy reports from ${{ github.sha }}"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}